### ISSUE TITLE
"Create Animated Machines" don't interact with chests and don't pick up items

### ISSUE THREAD

**Issue by SakulFlee** [OpenPlayVerse/ProjectCreate#2]
Create based Animated Machines don't interact with chests and don't pick up items from the ground.
Machines using _Mechanised Saw_ or _Mechanised Drill_ should be placing any items into attached chests once blocks break. 

They should only drop items on the ground due to special conditions (e.g. vines on Jungle trees) or if there is no Chest, accessible, found. Even if special conditions apply, upon the saw hitting a dropped item it should also be retrieved and put into a chest.

Furthermore, _Deployers_, with a set filter!, should pull content from any attached chest.
Putting e.g. saplings in a chest and setting the _Deployer_ filter to it _should_ plant those saplings.
This isn't happening either. **As if the chests don't exist or can't be accessed**.

This is also occurs in Single player, here's a world file with an example:
[Archive.tar.gz](https://github.com/user-attachments/files/17451908/Archive.tar.gz)

**Comment by Namelessys** [comment]
It's an issue with the 'Create: Interactive' mod. Which gets removed in v0.21.
